spring:
  datasource:
    url: jdbc:db2://localhost:25000/team2db
    username: db2admin
    password: db2admin
    driver-class-name: com.ibm.db2.jcc.DB2Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        debug: true  # Enable Hibernate debug mode
    database: db2
    database-platform: org.hibernate.dialect.DB2Dialect

logging:
  level:
    root: DEBUG

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
